spring:
  application:
    name: user-center

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Liang
    username: root
    password: root
  session:
    timeout: 86400



mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0



server:
  port: 8080
  servlet:
    context-path: /api